config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts do
    resources :comments
    get :favorites
    member { post :vote }
  end
  resources :favorite_posts, only: [:create, :destroy]

   root 'posts#index'
   match '/signup', to: 'users#new',         via: 'get'
   match '/signin', to: 'sessions#new',      via: 'get'
   match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts,  dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :favorite_posts, through: :favorites, source: :favorited, source_type: 'Post'
  before_save {self.email = email.downcase}
  before_create :create_remember_token
  validates :name, presence: true, length: {maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: {minimum: 8}

  def to_param
    "#{id}-#{name}"
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], :per_page => 5)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page], :per_page => 5 )
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile has been updated!'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
      if @user.save
        sign_in @user
        flash[:success] = 'Welcome to the Blog!'
        redirect_to @user
      else
        render 'new'
      end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted.'
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(signin_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_user.html.erb
<li style="list-style-type: none">
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  | <%= link_to 'Delete', user, method: :delete,
                                data: {confirm: 'Are you sure?'}%>
  <% end %>
</li>
<hr>

app/views/users/edit.html.erb
<h1 align="center">Update your profile</h1>

<div class="margin-left">
  <%= form_for @user do |f|%>
    <%= render 'shared/error_messages'%>

    <%= f.label :name%> <br>
    <%= f.text_field :name, palceholder: 'Name'%> <br>

    <%= f.label :email%> <br>
    <%= f.text_field :email, placeholder: 'E-mail'%> <br>

    <%= f.label :password%> <br>
    <%= f.password_field :password, placeholder: 'Password'%> <br>

    <%= f.label :password_confirmation%> <br>
    <%= f.password_field :password_confirmation, placeholder: 'Confirm password'%> <br>

    <%= f.submit 'Save changes', class: 'btn btn-large btn-primary'%> <br>
    <%= link_to 'Back to profile', user_path%>
  <% end %>
  <br>
  <%= gravatar_for @user%>
  <a href="http://gravatar.com/emails" target="blank">change</a>
</div>

app/views/users/index.html.erb
<h1 align="center">All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users%>
</ul>

<span class="paginate"><%= will_paginate %></span>

<%= link_to 'Profile', current_user %>

app/views/users/new.html.erb
<h1 class="margin-left">Sign up</h1>

<div class="margin-left">
    <%= form_for(@user) do |f|%>
      <%= render partial: 'shared/error_messages' %>
      <%= f.label :name %> <br>
      <%= f.text_field :name, placeholder: 'Name' %> <br>

      <%= f.label :email %> <br>
      <%= f.text_field :email, placeholder: 'E-mail' %> <br>

      <%= f.label :password %> <br>
      <%= f.password_field :password, placeholder: 'Password' %> <br>

      <%= f.label :password_confirmation %> <br>
      <%= f.password_field :password_confirmation, placeholder: 'Confirm your password' %> <br>

      <%= f.submit 'Create user', class: "btn btn-large btn-primary"%>
    <% end %>
</div>

<p class="margin-left">Or <%= link_to 'sign in', signin_path%></p>

app/views/users/show.html.erb
<% if signed_in?%>
<h1 align="center"><%= @user.name%>'s profile.</h1>

<h3 style="margin-left: 3px">
  <%= gravatar_for @user %> <%= link_to 'Edit profile:', edit_user_path%>
  <%= @user.name %>
</h3>
<% else %>
    <h1 align="center">Please <%= link_to 'sign in', new_session_path%></h1>
<% end %>
<br>
<div class="span8">
    <% if @user.posts.any? %>
      <h3 style="margin-left: 3px">Posts (<%= @user.posts.count %>) </h3>
      <ol class="microposts">
        <%= render @posts %>
      </ol>
      <span class="paginate"><%= will_paginate @posts %></span>
    <% end %>
  </div>