config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts do
    resources :comments
    get :favorites
    member { post :vote }
  end
  resources :favorite_posts, only: [:create, :destroy]

   root 'posts#index'
   match '/signup', to: 'users#new',         via: 'get'
   match '/signin', to: 'sessions#new',      via: 'get'
   match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  default_scope -> {order('created_at DESC')}
  validates_presence_of :title, :body, :user
  validates :title, length: { in: 5..140}
  validates :body, length: {minimum: 140}
  validates :user_id, presence: true

  has_reputation :votes,
      source: :user,
      aggregated_by: :sum

  acts_as_taggable

  def self.search(search)
    where("title LIKE ? OR body LIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def favorites
    @user = current_user
    @posts = @user.favorite_posts.all
  end

  def index
     @posts = unless params[:search].nil?
       Post.search(params[:search]).paginate(page: params[:page], :per_page => 5).find_with_reputation(:votes, :all, order: 'votes desc')
     else
       if params[:tag]
         @posts = Post.tagged_with(params[:tag]).paginate(page: params[:page], :per_page => 5)
       else
         @posts = Post.paginate(page: params[:page], :per_page => 5).find_with_reputation(:votes, :all, order: 'votes desc')
       end
     end
  end


  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new(post_id: :post)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    if current_user
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def vote
    @post = Post.find(params[:id])
    unless current_user == @post.user
      value = params[:type] == 'up' ? 1 : -1
      @post.add_or_update_evaluation(:votes, value, current_user)
      redirect_to :back, notice: 'Thank you for voting.'
    else
      redirect_to :back, notice: 'You must be logged in.'
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :tag_list).merge(user_id: current_user.id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, 'error') %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, placeholder: 'Body', class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tag_list, placeholder: 'Tags (separated by commas)', class: 'form-control' %>
  </div>
    <br>
  <div align="center" class="action">
   <%= f.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  = if @post.errors.any?
    %div #error_explanation
      %h2= pluralize(@post.errors.count, "error")
      %h2 prohibited this post from being saved:

      %ul
      = @post.errors.full_messages.each do |message|
        %li = message

  %div .field
    = f.label :title
    %br
    = f.text_field :title, placeholder: 'Title', :class => 'form-control'

  %div .field
    = f.label :body
    %br
    = f.text_area :body, placeholder: 'Body', :class => 'form-control'

  %div .field
    = f.label :tags
    %br
    = f.text_field :tags, placeholder: 'Tag', :class => 'form-control'

    %br
  %div .action {align="center"}
    = f.submit :class => 'btn btn-info'

app/views/posts/_post.html.erb
<li>
  <span><b><%= link_to post.title, post_path(post) %></b></span>
  <p align="justify"><span class="content"><%= post.body %></span></p>
  <span><%= raw post.tag_list.map{ |t| link_to t, tag_path(t) }.join(', ') %></span><br>
  <% unless current_user.favorite_posts.exists?(id: post.id) %>
      <%= link_to image_tag('star.png', size: '32x32'), favorite_posts_path(post_id: post), method: :post %>
  <% else %>
      <%= link_to image_tag('star_red.png', size: '32x32'), favorite_post_path(post), method: :delete %>
  <% end %>
  <br>
  <span><strong>Reputation: <%= post.reputation_for(:votes).to_i %></strong></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
  <p><b>Comments: <%= post.comments.count %></b></p>
</li>

app/views/posts/edit.html.haml
%h1 Editing Post

= render 'form'

%br
%div {align = "center"}
  = link_to image_tag('web-cam.png', size: '32x32'), @post
  = link_to image_tag('navigation-left.png', size: '32x32'), posts_path

app/views/posts/favorites.html.erb
<h1 align="center">Favorite posts</h1>

<div class="content">
  <ol>
    <% @posts.each do |fav| %>
      <p><b> <%= link_to fav.title, post_path(fav) %> </b></p>
      <p align="justify"> <%= fav.body %> </p>
    <% end %>
  </ol>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div align="right" id="middle">
  <%= form_tag(posts_path, method: 'GET') do%>
      <%= text_field_tag :search, params[:search], class: 'input-sm', placeholder: 'Search for...'%>
      <%= image_submit_tag('search.png', class: 'picture_size')%>

  <% end %>
</div>

<h1 align="center">Listing Posts</h1>

  <span class="paginate"> <%= will_paginate %> </span>

    <% @posts.each do |post| %>

    <div class="show_posts">
        <p align="center" style="margin-top: 1px"><b> <%= post.title %> </b> </p>
        <p style="margin-left: 3px; margin-right: 3px;" align="justify"><%= post.body %> </p>
        <p align="right" style="color: #2fa3ff; margin-right: 3px"> <%= raw post.tag_list.map{ |t| link_to t, tag_path(t) }.join(', ')%> </p>

      <div class="votes">
        <% unless current_user == post.user %>
          <%= link_to image_tag('arrow-up.png', size: '22x22'), vote_post_path(post, type: 'up'), method: 'post' %>
        <% end %>
        <strong><%= post.reputation_for(:votes).to_i %></strong>
        <% unless current_user == post.user %>
          <%= link_to image_tag('arrow-down.png', size: '22x22'), vote_post_path(post, type: 'down'), method: 'post' %>
        <% end %>
      </div>

      <div id="line" style="margin-top: 10px">
          <%= link_to image_tag('web-cam.png', size: '32x32'), post %>
          <% if current_user == post.user %>
            <%= link_to image_tag('pencil.png', size: '32x32'), edit_post_path(post) %>
            <%= link_to image_tag('bin.png', size: '32x32'), post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        <% if signed_in?%>
          <% unless current_user.favorite_posts.exists?(id: post.id) %>
              <%= link_to image_tag('star.png', size: '32x32'), favorite_posts_path(post_id: post), method: :post %>
          <% else %>
              <%= link_to image_tag('star_red.png', size: '32x32'), favorite_post_path(post), method: :delete %>
          <% end %>
        <% end %>
      </div>

     <div align="right" style="margin: auto; width: 170px; margin-bottom: 3px; margin-right: 3px">
       <% if post.user%>
         <table>
           <tr>
             <td rowspan="2"> <%= gravatar_for post.user, size: 40 %></td>
             <td>Created by:</td>
           </tr>
           <tr>
             <td><b><%= link_to post.user.name, post.user %></b></td>
           </tr>
         </table>
       <% end %>
     </div>
    </div>
  <% end %>
<br>


<% if signed_in?%>
  <div align="center">
    <a class="btn btn-info"<%= link_to 'New Post', new_post_path %> </a>
    <a class="btn btn-info"<%= link_to 'Back', current_user %> </a> <br>
  </div>
<% end %>

  <span class="paginate"> <%= will_paginate %> </span>

app/views/posts/new.html.haml
%h1 New Post

= render 'form'

%div {align="center">}
  = link_to 'Back', posts_path

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show_posts">
<p class="post-show">
  <strong>Title:</strong>
  <%= @post.try(:title) %>
</p>

<p class="post-show" style="margin-right: 3px" align="justify">
  <strong>Body:</strong>
  <%= @post.try(:body) %>
</p>

<p class="post-show">
  <strong>Tags:</strong>
  <%= raw @post.tag_list.map{ |t| link_to t, tag_path(t) }.join(', ') %>
</p>

  <div class="votes">
    <% unless current_user == @post.user %>
        <%= link_to image_tag('arrow-up.png', size: '22x22'), vote_post_path(@post, type: 'up'), method: 'post' %>
    <% end %>
    <strong><%= @post.reputation_for(:votes).to_i %></strong>
    <% unless current_user == @post.user %>
        <%= link_to image_tag('arrow-down.png', size: '22x22'), vote_post_path(@post, type: 'down'), method: 'post' %>
    <% end %>
  </div>

  <div style="margin-top: 10px" id="line">
    <% if current_user == @post.user %>
    <%= link_to image_tag('pencil.png', size: '32x32'), edit_post_path(@post) %>
    <% end %>
    <% unless current_user.favorite_posts.exists?(id: @post.id) %>
        <%= link_to image_tag('star.png', size: '32x32'), favorite_posts_path(post_id: @post), method: :post %>
    <% else %>
        <%= link_to image_tag('star_red.png', size: '32x32'), favorite_post_path(@post), method: :delete %>
    <% end %>
    <%= link_to image_tag('navigation-left.png', size: '32x32'), posts_path %>
  </div>

  <div align="right" style="margin: auto; width: 170px; margin-bottom: 3px; margin-right: 3px">
     <table>
           <tr>
             <td rowspan="2"> <%= gravatar_for @post.user, size: 40 %></td>
             <td>Created by:</td>
           </tr>
           <tr>
             <td><b><%= link_to @post.user.name, @post.user %></b></td>
           </tr>
         </table>
  </div>
  <hr>
  <h5 class="margin-comments" align="center"><strong>Comments:</strong></h5>

  <% @post.comments.each do |comment| %>
  <div align="left">
    <div class="post-show">
          <p>
            <%= comment.comment %>
          </p>
    </div>

    <div id="line_" style="margin-top: 10px">
      <% if comment.user == current_user %>
        <%= link_to image_tag('pencil.png', size: '30x30'), edit_post_comment_path(@post, comment) %>
        <%= link_to image_tag('bin.png', size: '30x30'), [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>

    <div  align="right" style="margin: auto; width: 170px; margin-bottom: 3px; margin-right: 3px">
      <table>
        <tr>
          <td rowspan="2"> <%= gravatar_for comment.user, size: 40 %></td>
          <td>Created by:</td>
        </tr>
        <tr>
          <td><b><%= link_to comment.user.name, comment.user %></b></td>
        </tr>
      </table>
    </div>
  </div>
     <% end %>

<%= render 'comments/form' %>

</div>