config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts do
    resources :comments
    get :favorites
    member { post :vote }
  end
  resources :favorite_posts, only: [:create, :destroy]

   root 'posts#index'
   match '/signup', to: 'users#new',         via: 'get'
   match '/signin', to: 'sessions#new',      via: 'get'
   match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_banner.html.erb
<script>
  $(function() {
      $( "#dialog" ).dialog();
    });
</script>
<div id="dialog" title="Attention!">
  <p> This place could be your advertisement! </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header class="navbar static-fixed-top navbar-inverse" id="bradius">
    <div class="navbar-inner">
      <div class="container">
        <div id="line">
        <%= link_to image_tag('linkedin.png', size: '50x50'), root_path%>
        </div>

        <div align="right" class="dropdown" id="middle">
          <% if signed_in?%>
             <span class="gravatar"> <%= gravatar_for current_user, size: 40%> </span>
          <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <%= current_user.name%>
              <span class="caret"></span>
          </button>
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
            <li><%= link_to 'Posts', posts_path%></li>
            <li><%= link_to 'My favorites', post_favorites_path(:post_id) %></li>
            <li><%= link_to 'Profile', current_user %></li>
            <li><%= link_to 'All users', users_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Log out', signout_path, method: 'delete'%></li>
          </ul>
        </div>
             <% else %>
        <nav>
          <ul class="nav pull-right">
            <li> </li>
            <li><%= link_to 'Sign in', new_session_path%></li>
          </ul>
        </nav>
              <% end %>
      </div>
    </div>
  </header>
  <div class="container">
    <%= yield %>
  </div>


 <div class="container">
  <div id="dialog">
    <p align="center"><strong> This place could be your advertisement!</strong> </p>
  </div>
 </div>

</body>
</html>